In [8]:
import pandas as pd
import numpy as np
import pickle
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
from matplotlib.pyplot import MultipleLocator

In [9]:
class EncodedDataset(Dataset):
    def __init__(self, datafile):
        super(EncodedDataset, self).__init__()
        self.data = []
        self.label = []
        self.length = []

        global input_size
        df = pd.read_csv(datafile, encoding='utf-8', sep=',', engine='python', error_bad_lines=False).drop(
            ['apdid', 'routermac'], axis=1)
        df_group = df.groupby(['target_event_id'], sort=False)
        drop_features = ['rn', 'target_event_id', 'label']
        input_size = df.shape[1] - len(drop_features)
        with tqdm(df_group, desc='loading data...') as loop:
            for target_event_id, frame in loop:
                if frame['rn'].iloc[0] != 1:
                    continue
                self.label.append(frame['label'].iloc[0])
                frame.sort_values(['rn'], inplace=True, ascending=False)
                x = frame.drop(drop_features, axis=1).to_numpy()
                
                self.data.append(x)
                self.length.append(len(x))

    def __len__(self):
        return len(self.label)

    def __getitem__(self, item):
        return self.data[item], self.label[item], self.length[item]


In [30]:
with open('HK_2020-01_KISA_hour_val_rep.pkl', "rb") as fp:
    data = pickle.load(fp)

In [31]:
data['label']

[array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], 

In [32]:
data['rep']

array([[-0.0210273 , -0.03725615, -0.03290382, ..., -0.03517652,
        -0.01993056,  0.00181087],
       [-0.05524636, -0.05861312, -0.0162297 , ..., -0.07326041,
         0.00063538,  0.01826411],
       [-0.03400445, -0.02031571, -0.03595433, ..., -0.03979229,
        -0.01387359, -0.00255604],
       ...,
       [ 0.22754958,  0.16154622, -0.20403665, ...,  0.09797332,
        -0.1112701 , -0.17887603],
       [ 0.25722772,  0.18329035, -0.22409983, ...,  0.11132203,
        -0.12094267, -0.2020128 ],
       [-0.06898603, -0.06005411, -0.02098571, ..., -0.09282932,
        -0.01357306,  0.03349321]], dtype=float32)

In [33]:
data['rep'].shape

(5419, 300)

In [34]:
np.array(data['label']).shape

(5419, 1)